### ISSUE TITLE
Possible to add filtering to requests?

### ISSUE THREAD

**Issue by mledford** [log0ymxm/node-harvest#11]
I'm grabbing data from the Reports section and I notice in Harvest's api they have the ability to filter the requests. For example you can ask to only return billable items. Is it possible to do this type of filtering? I don't see a way but I could be missing something obvious.

**Comment by guseng** [comment]
+1

**Comment by log0ymxm** [comment]
@peterbraden just added in some support for filtering billable items in the time entries by user report.

Here's his commit, https://github.com/log0ymxm/node-harvest/commit/4f2007d9566b5409eccd13971f1da5dd4c62d55a

It would still be nice to add in filters for the other reports as well.
