### ISSUE TITLE
Possibility to have project notes in Time Tracking?

### ISSUE THREAD

**Issue by marol87** [log0ymxm/node-harvest#19]
I'm using TimeTracking to get projects but project notes are not included. I can get notes from the Project section but I need the tasks from TimeTracking so I want to continue using the TimeTracking section. How can I get the notes while still using the projects data from the TimeTracking section?

**Comment by simplyspoke** [comment]
Due to the age of this issue, it will be closed unless more information can be provided in relation to the feature or bug described. A review of the code base suggests that the method works as it is intended or within the limitations presented by the Harvest API responces.
