### ISSUE TITLE
Deleting an entry gives a 404

### ISSUE THREAD

**Issue by marol87** [log0ymxm/node-harvest#23]
Hello,

I'm using the Node.js library and this is the code for deleting a time entry

https://github.com/log0ymxm/node-harvest/blob/master/lib/time-tracking.js#L74

As you can see the library makes an delete request and the url seems to be fine. 

for example
( /daily/delete/382707741 )

From angular.js I'm doing the this http call which is linked to a button:

```javascript
$scope.deleteTime = function(){

$http.post('/daily/delete', { entriesArray: $scope.entriesArray })

.then(function(response){

console.log(response);

if(response.data == "ok"){

console.log("Deleted time entries");

}

}, function(response){

console.log("error", response);

});

};
```

on the node.js side I'm doing

```javascript
router.post('/daily/delete', function(req, res) {

var harvest = new Harvest(req.session.user);

var entriesArray = req.body.entriesArray;

harvest.TimeTracking.delete(entriesArray[1], function(err, res){

console.log("Err");

console.log(err, res);

});

res.send("ok");

});
```

this gives me "{ status: '404', error: 'Not Found' } {}",

any idea why?

I've tried changing the request to a DELETE but in that way I have no way of sending any request data that in this case consists of an array of entries that I want to delete.

// Markus

**Comment by log0ymxm** [comment]
Is the 404 coming from your node.js endpoint, or the harvest API? It would help if you could post any logs or stack trace that come with this issue.

**Comment by log0ymxm** [comment]
Closed due to lack of information/response.
