### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by joeycozza** [log0ymxm/node-harvest#25]
Hey, I see in the Harvest docs that Invoices in particular use pagination 
```
By default Harvest will display 50 records per page. You can get further pages by passing in a page parameter.

GET /invoices?page=2
```

While looking through this module, I couldn't see where it handles pagination. 

Also, does anyone know if the other calls have a limit of records per page and are paginated?  The docs don't talk about pagination anywhere else that I could see.

**Comment by thomasnordquist** [comment]
There are currently 2 pull requests pending, addressing this issue: https://github.com/log0ymxm/node-harvest/pull/33, https://github.com/log0ymxm/node-harvest/pull/30

I currently overwrite the method to fix it till a solution arrives:

    harvest.Invoices.list = function (options, cb) {
        var url = '/invoices';
        options = options ? options : {};
        this.client.get(url, options, cb);
    };

It is worthy to mention that my solution does not comply with the official (and poor) api documentation.
Nevertheless the passed arguments will be recognized by the API.

This is how to use it:

    harvest.Invoices.list({page: 3}, cb);

**Comment by joeycozza** [comment]
Cool. Thanks for your thoughts and help with that.
