### ISSUE TITLE
How to oAuth

### ISSUE THREAD

**Issue by reini1989** [log0ymxm/node-harvest#26]
How to exacly use this with oAuth?
According to https://github.com/harvesthq/api/blob/master/Authentication/OAuth%202.0.md I must supply the user token at some point but I cant't find the point in the API to do so.

**Comment by log0ymxm** [comment]
Here's an example from the tests, https://github.com/log0ymxm/node-harvest/blob/master/test/harvest-client-tests.js#L16-L20

**Comment by reini1989** [comment]
Thanks log0ymxm. This is how far I got. 
However, if I then issue a request against one of the apis, I get an error that I am not authenticated. 
(yes, I did the redirect thingy) 

If you take a look at the link I posted above, the examples use the code from the back-redirect in the request as an access code. I can't find a way to supply this api with that code.
