### ISSUE TITLE
delete day entry gives [Error: deleting time requires an id]

### ISSUE THREAD

**Issue by marol87** [log0ymxm/node-harvest#31]
I'm using angular.js to send delete request to node using this:

```js
$http.delete('/daily/delete/' + entriesArray.id)
        .then(function(response){
                console.log(response);
                if(response.data == "ok"){
                    console.log("Deleted time entries");
                }
         }, function(response){
         console.log("error", response);
});
```

With express.js Router class I'm doing this call:
```js
router.delete('/daily/delete/:id', function(req, res) {
    var harvest = new Harvest(req.session.user);
    var id = req.params.id;
    harvest.TimeTracking.delete(id, function(err, res){
        if(err){
            console.log(err,res);
        } else{
            res.send("ok");
        } 
    });
});
```

The log of the request looks like this:
DELETE /daily/delete/id 
where id is correct from my entry.

But right after that log it gives an error log of:
[Error: deleting time requires an id] undefined

Where I'm doing it wrong, it seems it should work?

//Markus

**Comment by dnsl48** [comment]
Hi Markus,
You need to pass an object as the first argument, with `id` as a key. Like this:
```
var id = req.params.id;
harvest.TimeTracking.delete({ "id": id }, function(err, res) {})
```
Please use markdown styling for your messages in future.

**Comment by simplyspoke** [comment]
Added markdown to the initial issue and closing.
