### ISSUE TITLE
[SyntaxError: Failed to parse JSON body: Unexpected end of input]

### ISSUE THREAD

**Issue by whomwah** [log0ymxm/node-harvest#47]
Hi,

I'm trying to fetch a user using their email address and the syntax below, and am getting a JSON parse error thrown. Am I missing something in my syntax or is this an issue? The creds I'm using are an Admin user.

```
  var Harvest = require('harvest');
  var harvest = new Harvest({
    subdomain: config.env.HARVEST_SUBDOMAIN,
    email: config.env.HARVEST_EMAIL,
    password: config.env.HARVEST_PASSWORD
  });

  People = harvest.People;
  People.get({id: 'user@foo.com'}, function(err, user) {
    if (err) {
      console.log('An error occured', err);
      return;
    }

    /// do someting
  });
```

**Comment by lijoes3** [comment]
Hi, id needs to be integer. not the email. if you don't know the id. retrieve all users using 

 People.list({}, function(err, peoples) {
  })

then filter it it with email.

**Comment by whomwah** [comment]
@lijoes3 thanks, I'll see if that fixes things. Although I should note that the Harvest API states:

> Note: You may also pass a user's email address in place of a user_id.

https://github.com/harvesthq/api/blob/master/Sections/People.md#show-a-user

**Comment by simplyspoke** [comment]
Closing this issue due to age and the API documentation referenced is marked as outdated.
