### ISSUE TITLE
Pagination doesn't seem to be supported

### ISSUE THREAD

**Issue by blargity** [log0ymxm/node-harvest#54]
Is there a way to fetch more than 50 records? I notice that Harvest has pagination headers, so does this need to be supported in a generic way? It looks like there's an open PR for paginating just invoices, but in my use case I always want to make sure I have all of the data for a record type, so I think doing this generically would make the most sense.

**Comment by G3z** [comment]
well no :(, you should always ask for the next page and it should return an empty array if that page doesn't exists
it's a limit of harvest API http://help.getharvest.com/api/invoices-api/invoices/show-invoices/

**Comment by blargity** [comment]
That's not the problem, I'm happy to request the next page, I just can't figure out how to do that with this library. There doesn't seem to be any way to ask for another page of results from what I can tell. Could you show me how to request the second page of invoices with this library?

**Comment by simplyspoke** [comment]
Here is an example that should allow you to request a particular page of the invoices:

```js
  Invoices.list({page: 2}, function(err, invoices) {
    if (err) {
      return console.log('An error occured', err);
    }

    /// do someting
  });
```

If that answers the question, will plan on closing this issue and will plan to enhance the documentation in the near future.
