### ISSUE TITLE
Can't use slim and of_user in TimeTracking.daily

### ISSUE THREAD

**Issue by jayjanssen** [log0ymxm/node-harvest#56]
https://github.com/log0ymxm/node-harvest/blob/master/lib/time-tracking.js#L17-L27

Notice that setting 'slim' appends a '?' to the URL irrespective of whether of_user has been set or not.

**Comment by DerekDomino** [comment]
You may look at the recently merged PR that use append-query to handle the query string: https://github.com/log0ymxm/node-harvest/pull/55/files

**Comment by simplyspoke** [comment]
Closing as suggestion was already merged.
