### ISSUE TITLE
NPM version out of date

### ISSUE THREAD

**Issue by JWMarchant** [log0ymxm/node-harvest#63]
Hi there,

It seems that if I'm downloading your module from npm, it gives me version 0.2.0 rather than the current version in this repository of 0.2.9. 

James

**Comment by simplyspoke** [comment]
The harvest module has just undergone a rather large rewrite to version 1.x and npm has recently been updated. If you have already begun developing using 0.2.x, it would probably be a good idea to stick with that version unless you have time to adjust your code.

I will make sure that all new versions of the code update npm from here out.
