### ISSUE TITLE
addToAll Referenced in Documentation (But Removed?)

### ISSUE THREAD

**Issue by machineghost** [log0ymxm/node-harvest#64]
The tasks method `addToAll` is referenced on the front page documentation, but I can't find anything matching it in the Harvest documentation, and when I search for it in the repo I only see the README mention and a single test (which doesn't even seem to be testing `addToAll`).

Should this method perhaps be removed from the documentation (and that one test)?

**Comment by simplyspoke** [comment]
Good catch! Pushed a update.
