### ISSUE TITLE
Creating a client does not return ID

### ISSUE THREAD

**Issue by tim-soft** [log0ymxm/node-harvest#68]
Creating a client doesn't return an id in it's callback function. I've weasled around this by cutting it from res.headers.location

In an ideal world, all of these functions would return the callback data from doing a typical POST request to the Harvest api. 

In the least, these functions should return their respective id's

**Comment by simplyspoke** [comment]
I left a TODO on the lib/client.js to implement this feature as the current harvest api requests us to extract the id from the responce.headers.location. Over the next few days, I will set some time to work on it, otherwise if you want to submit a PR with an implementation for review, feel free.

**Comment by simplyspoke** [comment]
@tim-soft Just added this feature, the body now has an id property if creating new entities.
