### ISSUE TITLE
Access token config check

### ISSUE THREAD

**Issue by KuhArt** [log0ymxm/node-harvest#69]
https://github.com/log0ymxm/node-harvest/blob/552d0752989278d35bdb98c89b3bce0badbd32e4/lib/harvest.js#L40
 Should be:
```
helpers.has(config, ['accessToken'])
```

**Comment by simplyspoke** [comment]
Quite likely right.

I pulled this in from the prior version and I think there might have been a reason for it that was a patch on some other issue. Will try to review and sort in the next couple of days. Also should likely check that the tests are setup to see if OAuth works at the same time.

**Comment by KuhArt** [comment]
Please look at this commit https://github.com/KuhArt/node-harvest/commit/7b28a8d2281e37ed74b5609c84b8612b41cc31c4 . It should solve the problem.

**Comment by simplyspoke** [comment]
Remerged and tests passed
