### ISSUE TITLE
Provided access code was rejected by Harvest, no token was returned

### ISSUE THREAD

**Issue by jacquesletesson** [log0ymxm/node-harvest#72]
Hello there,

Is it possible that because I'm working locally I can't request an access token?

When I log the `response`in `setAccessToken` on line 107 I can see a 400 Bad Request.

```
{ server: 'nginx',
        date: 'Sat, 19 Aug 2017 20:46:47 GMT',
        'content-type': 'application/json',
        'content-length': '85',
        connection: 'close',
        status: '400 Bad Request',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        'x-content-type-options': 'nosniff',
        'cache-control': 'private, no-store, no-cache, max-age=0, must-revalidate',
        p3p: 'CP="Our privacy policy is available online: https://www.getharvest.com/services/privacy-policy"',
        'x-app-server': 'app12',
        'x-robots-tag': 'noindex, nofollow',
        'content-security-policy': 'report-uri /csp_reports; default-src *; img-src *; font-src data: cache.harvestapp.com; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' https://*.google-analytics.com https://*.nr-data.net https://ajax.googleapis.com cache.harvestapp.com https://js-agent.newrelic.com https://js.appcenter.intuit.com https://platform.twitter.com https://www.google.com https://www.googleadservices.com https://www.googletagmanager.com https://connect.facebook.net; style-src \'self\' \'unsafe-inline\' cache.harvestapp.com https://js.appcenter.intuit.com https://www.google.com',
        'x-request-id': '4a90bfe1d14f28f3da199a7ab882bb20',
        'x-runtime': '0.015621',
        'strict-transport-security': 'max-age=15552000; includeSubDomains' } },
  read: [Function] }
```

However my redirect url in Harvest is set to http://127.0.0.1:8080/oauth_redirect

**Comment by simplyspoke** [comment]
I did some experimenting and was able to recreate the response you got with a incorrect id and secrete pair. My guess is that some how your oauth credentials are off.

**Comment by jacquesletesson** [comment]
Well this is really weird.

I sandbox it on buddy.works and I got the same error.

My default.json looks like this :

```
{
  "harvest": {
    "subdomain": "xxxxxx",
    "identifier": "EuDkAJXhCgp2cWbM4L-P-x",
	"redirectUri": "http://127.0.0.1:8080/oauth_redirect",
    "secret": "Gd3nGp1_27XSP7vsWl-MTI7CXAATP-OTjQM95k43hOzqxl7rqDuVuyUXVlvyyUnMe3aJKCkJgfPLeq6LnR17xA",
    "userAgent": "node-harvest test runner"
  }
}
```

**Comment by simplyspoke** [comment]
I have been able to successfully run the tests of the oauth and the module seems to function as expected. Must shift to other things, but will check back in a few days in case this hasn't been resolved.

**Comment by jacquesletesson** [comment]
All the tests are working on my end as well.

When I try to generate a token via Postman with the same parameters, it works fine.

Will dig deeper...

![valid-token](https://user-images.githubusercontent.com/273400/29493170-92fba5a8-8591-11e7-8e5c-ecff34e86342.jpg)

**Comment by simplyspoke** [comment]
Curious,

You may want to make sure you have the latest version pulled down as I merged in some updates. Sounds like I will have to expand on the tests and etc when I get a min.

**Comment by simplyspoke** [comment]
With v2 of the API out, I will be shifting my efforts over to a new version of the module as their were some oddities with v1. Optimizing the return on effort and all that.

Will always be happy to have a look at a PR against v1 though.
