### ISSUE TITLE
params object holding on to old old options

### ISSUE THREAD

**Issue by tshamz** [log0ymxm/node-harvest#76]
I wrote a script that returns both the billable time and the total time tracked by a user in a given timespan. I'm making two calls using `reports.timeEntriesByUser`, with the same 'to' and 'from' property values in the params object, and adding the `billable: 'yes'` param in the call for only the billable entries. I'm running into an issue where the first time I fire off my requests via the client API, the entries I get back from each request are of the correct type (i.e. billable entries and all entries), however every request I make after that, I always get back the billable time entries regardless of what params I pass in.

At first I thought it might have been something I just overlooked, like passing in a reference to an object and then not updating it, or something like that, but I couldn't find anything. I started doing a little detective work, and I think I may have found something that's at the very least suspicious.  After turning on the debugger, In the callback for the request to the api, I logged the object that I passed as the params argument, as well as the `res.request.url.query` property on the `res` argument passed to the callback of the API request, and then compared to what the debugger said was happening. After restarting my server and triggering the first round of API requests, the debugger, my params objects, and the response data were all in step with one another. However, with any requests made after those first requests, the debugger and my console.logs agreed but the res data did not.

Below is a screenshot of my terminal output with some annotations and the function I'm using to hit up the API:

<img width="1067" alt="screen shot 2017-11-04 at 1 00 06 am" src="https://user-images.githubusercontent.com/2075200/32403668-fad078c4-c0fc-11e7-9823-e742c5b89315.png">

```
const getHours = (id, params, billable) => {
  const options = {from: params.from, to: params.to};
  if (billable) {
    options.billable = 'yes';
  }
  return new Promise((resolve, reject) => {
    harvest.reports.timeEntriesByUser(id, options, (err, res, timeEntries) => {
      console.dir({
        "options has billable property": options.hasOwnProperty('billable'),
        "options object": JSON.stringify(options),
        "request.url.query property on API res object": res.request.url.query
      });
      try {
        const hours = timeEntries.reduce((total, current) => total + current.day_entry.hours, 0);
        resolve(hours);
      } catch (error) {
        resolve(0);
      }
    });
  });
};
```

idk what exactly is going on, but it seems like the params are sticking or not getting cleared out after the first time they're used.

**Comment by tshamz** [comment]
nothing to see here...

**Comment by tshamz** [comment]
realized this might actually not be on my end so I'm reopening this.

**Comment by simplyspoke** [comment]
Looks like the client that would process the api requests was mutating its defaults, so once a property was set, it stayed set. I adjusted it to mutate a empty object which should sort your issue.

Once the tests complete, will merge and close the issue.
