### ISSUE TITLE
clients.get is throttling

### ISSUE THREAD

**Issue by odelucca** [log0ymxm/node-harvest#77]
Hey guys.

I am trying to run this code:

    let promise = new Promise((resolve, reject) => {
        harvest.clients.get(client_id, (error, res, body) => {
            resolve(body);
        });
    });

    return promise;

But I am getting this response from the API server:
`{ message: 'This request has been throttled.', retry_after: 15 }`

Every other function is working and returning a valid JSON. Can anybody help me with that one?

Just in case, I am using the basic auth, in this object here:

`let harvest = new Harvest({
        subdomain,
        email,
        password
    });`

**Comment by simplyspoke** [comment]
I would seem like you are hitting the throttling limit as mentioned on the following page:

https://help.getharvest.com/api-v1/introduction/overview/introduction/

There is a throttle check that I may add to the debug mode to get a sense of the limited while developing, but that would also take effort away from an update to the new v2 api. Do you have a means to monitor the outgoing requests of your script?
